controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: '/'
        fr: '/fr/'
    requirements:
        _locale: '|en|fr'
kernel:
    resource: ../../src/Kernel.php
    type: annotation
